//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int IdSchedule { get; set; }
        public string IdCar { get; set; }
        public string IdCustomer { get; set; }
        public string IdStaff { get; set; }
        public string Location { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> DateLocation { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdDetailed { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status Status { get; set; }
        public virtual Detailed_Schedule Detailed_Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
