//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int IdSchedule { get; set; }
        public string IdCar { get; set; }
        public string IdCustomer { get; set; }
        public string IdStaff { get; set; }
        public string Location { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> DateLocation { get; set; }
        public Nullable<int> IdStatus { get; set; }

        public Schedule()
        {
            // Constructor không tham số
        }

        public Schedule(int idSchedule, string idCar, string idStaff, string idCustomer, string location, DateTime? dateLocation, string destination, int? idStatus)
        {
            // Constructor có tham số
            this.IdSchedule = idSchedule;
            this.IdCar = idCar;
            this.IdStaff = idStaff;
            this.IdCustomer = idCustomer;
            this.Location = location;
            this.DateLocation = dateLocation;
            this.Destination = destination;
            this.IdStatus = idStatus;
        }

        public virtual Car Car { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Status Status { get; set; }
    }
}
